### ISSUE TITLE
Adding item doesn't scroll to correct location

### ISSUE THREAD

**Issue by chemmett** [shahroq/whale_manual_nav#2]
If you have a long list of items, clicking the "Add Item" button makes the dialog scroll way up the list instead of to the item you just added.

This line:
https://github.com/shahroq/whale_manual_nav/blob/d0270d079512aa113bda43a0ec4b880feb7c88fb/blocks/whale_manual_nav/form.php#L159
Should be using position() instead of offset() because we need the offset relative to the parent, not the offset on the screen.
`thisModal.animate({scrollTop: newItem.position().top},'slow');`

**Comment by MrKarlDilkington** [comment]
I can confirm this issue and the suggested fix appears to correct it.

**Comment by MrKarlDilkington** [comment]
@chemmett 

I recommend making a pull request with the proposed changes.

**Comment by shahroq** [comment]
I couldn't reproduce the issue. How many items do you have on your list? I make a list with more than 40 and it still seems fine? 
I also pushed an update. Can you confirm you see the same issue with the latest version, 1.3.1?
